/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2025-11-07 06:07:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.*;
import java.util.*;

public final class ingestiondata_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Program%20Files/eclipse/workspace/dailyMoldingWork_tomcat/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c.tld", Long.valueOf(1308094570000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1709434660000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	List<Product> list=(List<Product>)request.getAttribute("list");
	Product product=(Product)request.getAttribute("product");
	
	String flag=product == null ? "":String.valueOf(product.getFlag());
	String arrangementnumber=product == null ? "":String.valueOf(product.getArrangementnumber());
	String workperformancedate=product == null ? "":product.getWorkperformancedate();
	String id=product==null ? "":String.valueOf(product.getId());
	String err=(String)request.getAttribute("err");
	String msg=(String)request.getAttribute("msg");


      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("<!-- Bootstrap CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css\" integrity=\"sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M\" crossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Ingestiondata.css\">\n");
      out.write("<title>DailyMoldingWork</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container-fluid\" style=\"margin-top: 40px;\">\n");
      out.write("\n");
 if(err !=null){
      out.write("\n");
      out.write("<div class=\"alert alert-danger\" role=\"alert\">\n");
      out.print(err );
      out.write("\n");
      out.write("</div>\n");
} 
      out.write('\n');
 if(msg !=null){
      out.write("\n");
      out.write("<div class=\"alert alert-success\" role=\"alert\">\n");
      out.print(msg );
      out.write("\n");
      out.write("</div>\n");
} 
      out.write("\n");
      out.write("\n");
      out.write("<form action=\"");
      out.print( request.getContextPath() );
      out.write("/Ingestiondata\" method=\"GET\" class=\"form-inline\">\n");
      out.write("  <div class=\"form-row align-items-center\">\n");
      out.write("    <div class=\"form-group mr-3\">\n");
      out.write("      <input type=\"text\" id=\"searchInput\" name=\"searchKeyword\" class=\"form-control\" style=\"width: 600px; margin-top: 10px;\" placeholder=\"検索キーワードを入力してください\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group mx-sm-3\">\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\" style=\"margin-top: 10px;\" >検索</button>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<form action=\"");
      out.print( request.getContextPath() );
      out.write("/Ingestiondata\" method=\"post\" >\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("	<ul>\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main\">SingleData</a></li>\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/main2\">MultiData</a></li>\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/Ingestiondata\">Log</a></li>\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/BacklogList\">Backlog</a></li>\n");
      out.write("    	<li class=\"contact\">");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write(":ログイン中</li>\n");
      out.write("	</ul>\n");
      out.write("</header>\n");
      out.write("\n");
 if (list != null && !list.isEmpty()) { 
      out.write("\n");
      out.write("    <form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/Ingestiondata\">\n");
      out.write("        <button type=\"submit\" name=\"action\" value=\"deleteSelected\" class=\"btn btn-danger\" style=\"margin-top: 10px;\" onclick=\"return confirm('選択した項目を削除してよろしいですか？');\">\n");
      out.write("            選択項目 削除\n");
      out.write("        </button>\n");
      out.write("        <button type=\"submit\" name=\"action\" value=\"downloadSelected\" class=\"btn btn-success\" style=\"margin-top: 10px;\" onclick=\"return confirmAndDisableSelected();\">\n");
      out.write("        	選択項目 CSV\n");
      out.write("        </button>\n");
      out.write("\n");
      out.write("        <table class=\"table table-striped mt-4\">\n");
      out.write("            <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th><input type=\"checkbox\" id=\"selectAll\" onclick=\"toggleSelectAll(this)\"> 全選択</th>\n");
      out.write("                    <th>フラグ</th>\n");
      out.write("                    <th>作業実績日</th>\n");
      out.write("                    <th>手配番号</th>\n");
      out.write("                    <th>機械コード</th>\n");
      out.write("                    <th>日勤夜勤区分</th>\n");
      out.write("                    <th>備考</th>\n");
      out.write("                    <th>操作項目</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("                ");
 for (Product p : list) { 
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td><input type=\"checkbox\" name=\"selectedIds\" value=\"");
      out.print( p.getId() );
      out.write("\"></td>\n");
      out.write("                    <td>");
      out.print( p.getFlag() );
      out.write("\n");
      out.write("                        <input type=\"hidden\" name=\"flag_");
      out.print( p.getId() );
      out.write("\" value=\"");
      out.print( p.getFlag() );
      out.write("\"> <!-- フラグを隠しフィールドとして送信 -->\n");
      out.write("                    </td>\n");
      out.write("                    <td>");
      out.print( p.getWorkperformancedate() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( p.getArrangementnumber() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( p.getMachinecode() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( p.getWorkinghours() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( p.getRemarks() );
      out.write("</td>\n");
      out.write("                    <td>\n");
      out.write("                        ");
 if(p.getFlag() == 1) { 
      out.write("\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/main?action=update&id=");
      out.print(String.valueOf(p.getId()) );
      out.write("\" class=\"btn btn-primary\">更新</a>\n");
      out.write("                        ");
 } else if(p.getFlag() == 2) { 
      out.write("\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/main2?action=update&id=");
      out.print(String.valueOf(p.getId()) );
      out.write("\" class=\"btn btn-primary\">更新</a>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/Ingestiondata?action=delete&id=");
      out.print( p.getId() );
      out.write("\" class=\"btn btn-danger\" onclick=\"return confirm('削除してよろしいですか？');\">\n");
      out.write("                            削除\n");
      out.write("                        </a>\n");
      out.write("                        ");
 if (p.getFlag() == 1 || p.getFlag() == 2) { 
      out.write("\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/Ingestiondata?action=");
      out.print( p.getFlag() == 1 ? "download" : "download2" );
      out.write("&id=");
      out.print( p.getId() );
      out.write("\" \n");
      out.write("                            	id=\"downloadBtn_");
      out.print( p.getId() );
      out.write("\" class=\"btn btn-success\" onclick=\"return confirmDownload('ダウンロードしてよろしいですか？', '");
      out.print( p.getId() );
      out.write("');\">\n");
      out.write("                            	CSV\n");
      out.write("                            </a>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </form>\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("	<ul>\n");
      out.write("    	<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/Logout\">Logout</a></li>\n");
      out.write("	</ul>\n");
      out.write("</footer>\n");
      out.write(" \n");
      out.write("</form>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("const forms=document.getElementsByClassName(\"form-control\");\n");
      out.write("const alerts=document.getElementsByClassName(\"alert\");\n");
      out.write("for(let i=0;i<forms.length;i++){\n");
      out.write("	forms[i].addEventListener(\"focus\",()=>{\n");
      out.write("		for(let j=0;j<alerts.length;j++){\n");
      out.write("			alerts[j].style.display=\"none\";\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("}\n");
      out.write("\n");
      out.write("<!-- リロード制御 -->\n");
      out.write("if (!sessionStorage.getItem('reloaded')) {\n");
      out.write("  sessionStorage.setItem('reloaded', 'true');\n");
      out.write("  window.location.reload();\n");
      out.write("} else {\n");
      out.write("  sessionStorage.removeItem('reloaded');\n");
      out.write("}\n");
      out.write("\n");
      out.write("<!-- ダウンロードを確認する関数  -->\n");
      out.write("function confirmDownload(message, id) {\n");
      out.write("    // 確認ダイアログを表示し、結果を取得する\n");
      out.write("    var confirmed = confirm(message);\n");
      out.write("    // ダウンロードがキャンセルされた場合はfalseを返す\n");
      out.write("    if (!confirmed) {\n");
      out.write("        return false;\n");
      out.write("    }\n");
      out.write("    // ボタンを非アクティブにする\n");
      out.write("    var downloadBtn = document.getElementById('downloadBtn_' + id);\n");
      out.write("    if (downloadBtn) {\n");
      out.write("        downloadBtn.classList.add('disabled');\n");
      out.write("        downloadBtn.classList.remove('btn-success');\n");
      out.write("        downloadBtn.classList.add('btn-dark');\n");
      out.write("        downloadBtn.style.backgroundColor = 'black';\n");
      out.write("    }\n");
      out.write("    // ボタンの状態をセッションストレージに記録する\n");
      out.write("    sessionStorage.setItem('downloadBtnDisabled_' + id, 'true');\n");
      out.write("    return true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("<!-- ページロード時にボタンの状態を復元する  -->\n");
      out.write("window.onload = function() {\n");
      out.write("    ");
 for(Product p : list) { 
      out.write("\n");
      out.write("        var isDisabled_");
      out.print( p.getId() );
      out.write(" = sessionStorage.getItem('downloadBtnDisabled_");
      out.print( p.getId() );
      out.write("');\n");
      out.write("        if (isDisabled_");
      out.print( p.getId() );
      out.write(" === 'true') {\n");
      out.write("            var downloadBtn_");
      out.print( p.getId() );
      out.write(" = document.getElementById('downloadBtn_");
      out.print( p.getId() );
      out.write("');\n");
      out.write("            if (downloadBtn_");
      out.print( p.getId() );
      out.write(") {\n");
      out.write("                downloadBtn_");
      out.print( p.getId() );
      out.write(".classList.add('disabled');\n");
      out.write("                downloadBtn_");
      out.print( p.getId() );
      out.write(".classList.remove('btn-success');\n");
      out.write("                downloadBtn_");
      out.print( p.getId() );
      out.write(".classList.add('btn-dark');\n");
      out.write("                downloadBtn_");
      out.print( p.getId() );
      out.write(".style.backgroundColor = 'black';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("};\n");
      out.write("\n");
      out.write("<!-- チェックボックスの全選択/全解除用  -->\n");
      out.write("function toggleSelectAll(source) {\n");
      out.write("    const checkboxes = document.getElementsByName('selectedIds');\n");
      out.write("    for (let i = 0; i < checkboxes.length; i++) {\n");
      out.write("      checkboxes[i].checked = source.checked;\n");
      out.write("    }\n");
      out.write("  }\n");
      out.write("\n");
      out.write("<!-- チェックが1つもない場合に警告を表示する関数  -->\n");
      out.write("function validateSelection() {\n");
      out.write("  const checkboxes = document.querySelectorAll('input[name=\"selectedIds\"]:checked');\n");
      out.write("  if (checkboxes.length === 0) {\n");
      out.write("    alert('少なくとも1つの項目を選択してください。');\n");
      out.write("    return false;  // フォーム送信を中止\n");
      out.write("  }\n");
      out.write("  return true;  // フォーム送信を実行\n");
      out.write("}\n");
      out.write("\n");
      out.write("<!-- チェックボックスのダウンロードを確認する関数  -->\n");
      out.write("function confirmAndDisableSelected() {\n");
      out.write("    // 確認ダイアログを表示\n");
      out.write("    var confirmed = confirm('選択した項目をダウンロードしてよろしいですか？');\n");
      out.write("    \n");
      out.write("    // ユーザーがキャンセルした場合は処理を終了\n");
      out.write("    if (!confirmed) {\n");
      out.write("        return false;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    // チェックされたチェックボックスを取得\n");
      out.write("    var selectedCheckboxes = document.querySelectorAll('input[name=\"selectedIds\"]:checked');\n");
      out.write("    \n");
      out.write("    selectedCheckboxes.forEach(function(checkbox) {\n");
      out.write("        // チェックボックスの値（id）を取得し、それに対応するボタンを無効化\n");
      out.write("        var id = checkbox.value;\n");
      out.write("        var downloadBtn = document.getElementById('downloadBtn_' + id);\n");
      out.write("        \n");
      out.write("        if (downloadBtn) {\n");
      out.write("            // ボタンを無効化し、スタイルを変更\n");
      out.write("            downloadBtn.classList.add('disabled');\n");
      out.write("            downloadBtn.classList.remove('btn-success');\n");
      out.write("            downloadBtn.classList.add('btn-dark');\n");
      out.write("            downloadBtn.style.backgroundColor = 'black';\n");
      out.write("            \n");
      out.write("            // 状態をセッションストレージに記録\n");
      out.write("            sessionStorage.setItem('downloadBtnDisabled_' + id, 'true');\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    return true; // ダウンロード処理を続行\n");
      out.write("}\n");
      out.write("\n");
      out.write("<!-- ページロード時にボタンの状態を復元する  -->\n");
      out.write("window.onload = function() {\n");
      out.write("    // すべての商品IDに対応するボタンの状態を確認して復元\n");
      out.write("    var allProducts = document.querySelectorAll('input[name=\"selectedIds\"]');\n");
      out.write("    allProducts.forEach(function(product) {\n");
      out.write("        var id = product.value;\n");
      out.write("        var isDisabled = sessionStorage.getItem('downloadBtnDisabled_' + id);\n");
      out.write("        if (isDisabled === 'true') {\n");
      out.write("            var downloadBtn = document.getElementById('downloadBtn_' + id);\n");
      out.write("            if (downloadBtn) {\n");
      out.write("                downloadBtn.classList.add('disabled');\n");
      out.write("                downloadBtn.classList.remove('btn-success');\n");
      out.write("                downloadBtn.classList.add('btn-dark');\n");
      out.write("                downloadBtn.style.backgroundColor = 'black';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("};\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/view/ingestiondata.jsp(61,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
